### ISSUE TITLE
How to Use?

### ISSUE THREAD

**Issue by drwebmonkey** [mergehez/vscode-json-file-synchronizer#1]
Looks promising, but how to start?
I see the Arg: JSON File Synchronizer in commands, but it only provides a blank looking page with Arg JSON File Synchronizer at the top, no config button as shown in sample.

**Comment by alexandre-machado** [comment]
☝🏾

**Comment by mergehez** [comment]
I've updated the extension. Now it should be clear how to use it. Can you update it and see if it is good for you?
